[package]
name = "instruction_decoder"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8"
derivative = "2"
env_logger = "0.11"
itertools = "0.14"
log = "0.4"
proc-macro2 = "1"
quote = "1"

[lib]
proc-macro = true
